project:
  type: website

website:
  title: "Position Zero!"
  navbar:
    right:
      - about.qmd
      - text: Posts
        href: posts/index.qmd
      - icon: github
        href: https://github.com/Jacen-cpu
      - icon: twitter
        href: https://twitter.com/Jacen57745631
    background: "#3271a8"
  sidebar:
    style: "floating"
    contents: 
      - section: "computer science"
        contents: posts/*/
    background: "#fafbfc"
  favicon: favicon.png
  reader-mode: true
  page-navigation: true
  page-footer: "Copyright © 2020, Proudyang" 

format:
  html:
    page-layout: article
    css: css/styles.css
    theme: litera
    smmooth-scroll: true
    link-external-newwindow: true
    citation-hover: true
    footnotes-hover: true
    toc: true
    toc-title: Contents
    html-math-method: katex
    code-link: true

editor: visual

execute:
  freeze: auto
